---
version: '3'
services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - ./docker_data/darth_data:/var/lib/postgresql/data
    env_file:
      - "docker/${MIX_ENV}.env"
    restart: always

  fader360_backend:
    build:
      context: ./docker
      target: darth_release
      args:
        - MIX_ENV
    image: "${DOCKER_IMAGE}:${DOCKER_TAG}"
    ports:
      - "45000:45000"
    volumes:
      - ./docker_data/media:/root/darth_release/lib/darth-${VERSION}/priv/static/media
      - ./docker_data/preview_download:/root/darth_release/lib/darth-${VERSION}/priv/static/preview_download
    depends_on:
      - db
    environment:
      - MIX_ENV
    env_file:
      - "docker/${MIX_ENV}.env"
    restart: always

  darth_dev:
    build:
      context: ./docker
      target: darth_base
      args:
        - MIX_ENV
    ports:
      - "45000:45000"
    depends_on:
      - db
    command:
      - "make run"
    volumes:
      - ./docker_data/media:/work/priv/static/media
      - ./docker_data/preview_download:/work/priv/static/preview_download
    environment:
      - MIX_ENV
    env_file:
      - "docker/${MIX_ENV}.env"

  darth_refresh_db:
    build:
      context: ./docker
      target: darth_base
      args:
        - MIX_ENV
    depends_on:
      - db
    command:
      - "make refresh-db"
    environment:
      - MIX_ENV
    env_file:
      - "docker/${MIX_ENV}.env"

  darth_migrate_db:
    build:
      context: ./docker
      target: darth_base
      args:
        - MIX_ENV
    depends_on:
      - db
    command:
      - "make migrate-db"
    environment:
      - MIX_ENV
    env_file:
      - "docker/${MIX_ENV}.env"
